version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vocab_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  db-init:
    build:
      context: .
      dockerfile: db-init/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/vocab_app
      POSTGRES_HOST: postgres
      POSTGRES_DB: vocab_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
    volumes:
      - ./:/app:cached

volumes:
  db_data:
